import { useState } from 'react'
import './index.css'

type ProjectCategory = 'All' | 'Full-stack' | 'AI / ML' | 'Computer vision'
type Project = { name: string; category: Exclude<ProjectCategory, 'All'>; number: string; description: string; stack: string[]; accent: string; visual: string }

const github = 'https://github.com/praveenkumar21122006'
const portfolio = 'https://keen-petal-66cy5nz.shipstatic.com'
const projects: Project[] = [
  { name: 'Travel Planner', category: 'Full-stack', number: '01', description: 'A complete trip-building workspace with live weather, city discovery, and a clean itinerary flow.', stack: ['React', 'TypeScript', 'Prisma', 'PostgreSQL'], accent: 'mint', visual: 'TRIP / 05 DAYS' },
  { name: 'Driver Safety Monitor', category: 'Computer vision', number: '02', description: 'Local-first driver fatigue and distraction detection with webcam landmarks and audio warnings.', stack: ['JavaScript', 'MediaPipe', 'Vercel'], accent: 'coral', visual: 'ALERT / ACTIVE' },
  { name: 'Retail Management Copilot', category: 'AI / ML', number: '03', description: 'An evidence-based AI assistant that turns inventory and sales data into useful answers.', stack: ['Python', 'Gemini API', 'Streamlit'], accent: 'blue', visual: 'ASK / ANALYZE' },
  { name: 'Patient Triage Assistant', category: 'Full-stack', number: '04', description: 'Clinic intake and triage dashboard built around a deterministic five-level care engine.', stack: ['Node.js', 'SQLite', 'Express'], accent: 'yellow', visual: 'ESI / LEVEL 03' },
  { name: 'Workplace Safety Monitor', category: 'Computer vision', number: '05', description: 'Real-time PPE compliance using YOLOv8, browser video, and sustained-violation alerts.', stack: ['Python', 'YOLOv8', 'Streamlit'], accent: 'coral', visual: 'PPE / 94%' },
  { name: 'Fake URL Detector', category: 'AI / ML', number: '06', description: 'A threat-scoring web app that identifies phishing patterns in URLs in real time.', stack: ['Python', 'Flask', 'Scikit-learn'], accent: 'blue', visual: 'RISK / LOW' },
  { name: 'Bus Attendance System', category: 'Computer vision', number: '07', description: 'Face-recognition attendance for school buses with unknown-person photo logging.', stack: ['Python', 'Flask', 'SQLite'], accent: 'mint', visual: 'ROUTE / 08:45' },
  { name: 'Transaction Risk Management', category: 'Full-stack', number: '08', description: 'A focused review dashboard for evaluating financial transactions with a Python API.', stack: ['React', 'Vite', 'REST API'], accent: 'yellow', visual: 'RISK / REVIEW' },
  { name: 'P2P Chat App', category: 'Full-stack', number: '09', description: 'A Dockerized real-time chat experience using secure WebSocket communication.', stack: ['Node.js', 'WebSockets', 'Docker'], accent: 'blue', visual: 'LIVE / 12 USERS' },
  { name: 'Fake Account Detection', category: 'AI / ML', number: '10', description: 'A machine-learning classifier for spotting suspicious social account behavior.', stack: ['Python', 'Scikit-learn', 'ML'], accent: 'coral', visual: 'SCORE / 0.87' },
  { name: 'Live Resource Mapper', category: 'Full-stack', number: '11', description: 'A real-time dashboard that turns system and network resource activity into a live map.', stack: ['JavaScript', 'Node.js', 'WebSockets'], accent: 'mint', visual: 'STREAM / ONLINE' },
]

const skillGroups = [['Languages', 'Java · Python · JavaScript'], ['Web / backend', 'HTML5 · CSS3 · Node.js · Express.js · Flask · REST API · WebSockets'], ['AI / ML / CV', 'Scikit-learn · OpenCV · MediaPipe · dlib · NLP'], ['Data', 'MySQL · SQLite · JSON-based storage'], ['Tools', 'Git · GitHub · Docker · VS Code · Arduino · Tkinter']]

function Arrow() { return <span aria-hidden="true" className="arrow">↗</span> }

function App() {
  const [activeCategory, setActiveCategory] = useState<ProjectCategory>('All')
  const [menuOpen, setMenuOpen] = useState(false)
  const visibleProjects = activeCategory === 'All' ? projects : projects.filter((project) => project.category === activeCategory)
  const closeMenu = () => setMenuOpen(false)

  return <div className="site-shell">
    <header className="topbar"><a className="brand" href="#top" onClick={closeMenu}><span className="brand-mark">PK</span><span>Praveen Kumar N</span></a><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}><a href="#work" onClick={closeMenu}>Work</a><a href="#about" onClick={closeMenu}>About</a><a href="#contact" onClick={closeMenu}>Contact</a><a className="nav-cta" href={github} target="_blank" rel="noreferrer">GitHub <Arrow /></a></nav></header>
    <main id="top">
      <section className="hero section-wrap"><div className="hero-copy reveal"><p className="eyebrow"><span className="status-dot" /> Available for internships & collaborations</p><h1>Building useful<br /><em>intelligence.</em></h1><p className="hero-intro">I’m Praveen, a CSBS student who turns messy problems into thoughtful full-stack products, machine-learning tools, and computer-vision systems.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <Arrow /></a><a className="text-link" href="mailto:praveenkumarnagaraj83@gmail.com">Let’s talk <Arrow /></a></div></div><div className="hero-aside reveal reveal-delay"><div className="signal-card"><div className="signal-top"><span>BUILD SIGNAL</span><span>2026 / 09</span></div><div className="signal-lines"><span /><span /><span /></div><div className="signal-foot"><strong>11</strong><small>deployed<br />projects</small><strong>8.10</strong><small>current<br />CGPA</small></div></div><p className="aside-note">From a webcam frame to a financial risk score, I like working where software meets the real world.</p></div></section>
      <div className="ticker" aria-label="Areas of focus"><div className="ticker-track"><span>FULL-STACK DEVELOPMENT</span><i>✳</i><span>ARTIFICIAL INTELLIGENCE</span><i>✳</i><span>COMPUTER VISION</span><i>✳</i><span>FULL-STACK DEVELOPMENT</span><i>✳</i><span>ARTIFICIAL INTELLIGENCE</span></div></div>
      <section className="work section-wrap" id="work"><div className="section-heading"><div><p className="eyebrow">Selected experiments</p><h2>Work that<br /><em>does something.</em></h2></div><p className="section-summary">A growing collection of shipped ideas across product engineering, applied AI, and visual intelligence.</p></div><div className="filter-row" role="group" aria-label="Filter projects">{(['All', 'Full-stack', 'AI / ML', 'Computer vision'] as ProjectCategory[]).map((category) => <button className={activeCategory === category ? 'filter active' : 'filter'} key={category} onClick={() => setActiveCategory(category)}>{category}<span>{category === 'All' ? projects.length : projects.filter((project) => project.category === category).length}</span></button>)}</div><div className="project-grid">{visibleProjects.map((project) => <article className={`project-card ${project.accent}`} key={project.name}><div className="project-visual"><div className="visual-grid" /><span className="visual-label">{project.visual}</span><span className="project-number">{project.number}</span><div className="visual-bars"><b /><b /><b /><b /></div></div><div className="project-body"><div className="project-meta"><span>{project.category}</span><a href={github} target="_blank" rel="noreferrer" aria-label={`View ${project.name} on GitHub`}>GitHub <Arrow /></a></div><h3>{project.name}</h3><p>{project.description}</p><div className="tag-row">{project.stack.map((tag) => <span key={tag}>{tag}</span>)}</div></div></article>)}</div></section>
      <section className="about section-wrap" id="about"><div className="section-heading about-heading"><div><p className="eyebrow">A little context</p><h2>Curious by<br /><em>default.</em></h2></div><p className="section-summary">I’m currently pursuing my B.Tech in Computer Science & Business Systems at VSB Engineering College, Karur. I care about products that are clear, resilient, and kind to their users.</p></div><div className="about-grid"><div className="timeline"><div className="timeline-item"><span className="timeline-date">2026 — NOW</span><div><h3>Software Development Virtual Intern</h3><p>Infosys Springboard · Remote</p><small>Built workflow fluency through a crypto portfolio manager project, Git collaboration, and Python data processing.</small></div></div><div className="timeline-item"><span className="timeline-date">2024 — 2028</span><div><h3>B.Tech · CSBS</h3><p>VSB Engineering College, Karur</p><small>Current CGPA: 8.10 / 10</small></div></div></div><div className="skills-list">{skillGroups.map(([name, skills]) => <div className="skill-row" key={name}><span>{name}</span><strong>{skills}</strong></div>)}</div></div></section>
      <section className="contact section-wrap" id="contact"><div className="contact-panel"><div><p className="eyebrow">Have a problem worth solving?</p><h2>Let’s make<br /><em>something real.</em></h2></div><div className="contact-side"><p>Open to full-time roles, internships, and collaborative projects where I can contribute from day one.</p><a className="button button-light" href="mailto:praveenkumarnagaraj83@gmail.com">Start a conversation <Arrow /></a></div></div></section>
    </main><footer className="footer section-wrap"><span>© 2026 Praveen Kumar N</span><div><a href={github} target="_blank" rel="noreferrer">GitHub <Arrow /></a><a href={portfolio} target="_blank" rel="noreferrer">Portfolio <Arrow /></a><a href="mailto:praveenkumarnagaraj83@gmail.com">Email <Arrow /></a></div></footer>
  </div>
}

export default App